import * as React from "react"
import { Accordion } from "./accordion"


export const VacancyItems = () => {
  const config  = [
    {
      title:'Дизайнер без опыта после вуза',
      text:'<p class="vacancy_faq_item_p_bold">От&nbsp;вас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Высшее архитектурное образование (БНТУ, Академия искусств).</li><li class="vacancy_faq_item_li">Уверенное владение программами 3Ds Max+Corona, Adobe Photoshop, AutoCad, SketchUp (приветствуется).</li><li class="vacancy_faq_item_li">Хороший уровень 3D визуализации.</li><li class="vacancy_faq_item_li">Умение рисовать от&nbsp;руки (развитый художественный вкус).</li><li class="vacancy_faq_item_li">Любовь к&nbsp;профессии и&nbsp;желание развиваться в&nbsp;сфере дизайна интерьера.</li></ul><p class="vacancy_faq_item_p_bold">От&nbsp;нас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Участие в&nbsp;интересных проектах.</li><li class="vacancy_faq_item_li">Работа под руководством опытных архитекторов и&nbsp;дизайнеров студии (менторинг).</li><li class="vacancy_faq_item_li">Тренинги от&nbsp;партнеров студии для ориентации в&nbsp;рынке материалов и&nbsp;технологий.</li><li class="vacancy_faq_item_li">Выезды на&nbsp;строящие объекты студии для обучения ведению авторского надзора.</li><li class="vacancy_faq_item_li">Участие в&nbsp;мозговых штурмах и&nbsp;workshop.</li><li class="vacancy_faq_item_li">Возможность распределения после ВУЗа/либо оплачиваемая стажировка.</li><li class="vacancy_faq_item_li">Лучших молодых специалистов берем с&nbsp;собой в&nbsp;зарубежные поездки на&nbsp;выставки и&nbsp;предприятия.</li></ul><div class="vacancy_faq_item_flex"><div class="vacancy_faq_item_flex_text"><p class="vacancy_faq_item_p">Будет здорово, если перед отправкой резюме и&nbsp;портфолио вы&nbsp;чуть больше узнаете о&nbsp;нашей студии. О&nbsp;нашей специализации и&nbsp;подходе к&nbsp;проектам мы&nbsp;рассказываем в&nbsp;разделах &laquo;Портфолио&raquo; и&nbsp;&laquo;О&nbsp;студии&raquo;. Загляните туда, это поможет составить представление о&nbsp;том, чем вам предстоит заниматься.</p><p class="vacancy_faq_item_p">В&nbsp;нашей команде нет случайных людей. Больше всего в&nbsp;сотрудниках мы&nbsp;ценим готовность трудиться и&nbsp;любовь к&nbsp;дизайну. Чтобы попасть в&nbsp;нашу команду вам нужно будет выполнить небольшое креативное задание. Оно не&nbsp;займет много времени, но&nbsp;поможет нам лучше познакомиться с&nbsp;вами.</p></div><div class="vacancy_faq_item_flex_mail"><p class="vacancy_faq_item_flex_mail_p">Резюме вы&nbsp;можете отправить на&nbsp;почту:</p><a href="mailto:o.rasseko@gmail.com" class="vacancy_faq_item_flex_mail_a">o.rasseko@gmail.com</a></div></div>'
    },
    {
      title:'Дизайнер интерьера с&nbsp;опытом работы',
      text:'<p class="vacancy_faq_item_p_bold">От&nbsp;вас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Высшее архитектурное образование (БНТУ, Академия искусств).</li><li class="vacancy_faq_item_li">Профессиональное владение программами 3Ds Max+Corona, Adobe Photoshop, AutoCad, SketchUp (приветствуется).</li><li class="vacancy_faq_item_li">Высокий уровень 3D визуализации.</li><li class="vacancy_faq_item_li">Опыт ведения проектов от&nbsp;разработки до&nbsp;реализации (от&nbsp;3&nbsp;лет).</li><li class="vacancy_faq_item_li">Развитый визуальный вкус.</li><li class="vacancy_faq_item_li">Любовь к&nbsp;профессии и&nbsp;желание развиваться в&nbsp;сфере дизайна интерьера.</li></ul><p class="vacancy_faq_item_p_bold">От&nbsp;нас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Работа с&nbsp;ключевыми объектами студии (большие бюджеты и&nbsp;площади).</li><li class="vacancy_faq_item_li">Посещение зарубежных выставок, предприятий, спецпроектов и&nbsp;семинаров.</li><li class="vacancy_faq_item_li">Кураторство над молодыми специалистами (по&nbsp;желанию).</li><li class="vacancy_faq_item_li">Карьерный рост до&nbsp;арт-директора студии.</li><li class="vacancy_faq_item_li">Обучающие семинары, посвященные психологии общения с&nbsp;заказчиками, новым технологиям и&nbsp;материалам в&nbsp;сфере интерьерного проектирования и&nbsp;др.</li><li class="vacancy_faq_item_li">Авторство проектов.</li></ul><div class="vacancy_faq_item_flex"><div class="vacancy_faq_item_flex_text"><p class="vacancy_faq_item_p">Будет здорово, если перед отправкой резюме и&nbsp;портфолио вы&nbsp;чуть больше узнаете о&nbsp;нашей студии. О&nbsp;нашей специализации и&nbsp;подходе к&nbsp;проектам мы&nbsp;рассказываем в&nbsp;разделах &laquo;Портфолио&raquo; и&nbsp;&laquo;О&nbsp;студии&raquo;. Загляните туда, это поможет составить представление о&nbsp;том, чем вам предстоит заниматься.</p><p class="vacancy_faq_item_p">В&nbsp;нашей команде нет случайных людей. Больше всего в&nbsp;сотрудниках мы&nbsp;ценим готовность трудиться и&nbsp;любовь к&nbsp;дизайну. Чтобы попасть в&nbsp;нашу команду вам нужно будет выполнить небольшое креативное задание. Оно не&nbsp;займет много времени, но&nbsp;поможет нам лучше познакомиться с&nbsp;вами.</p></div><div class="vacancy_faq_item_flex_mail"><p class="vacancy_faq_item_flex_mail_p">Резюме вы&nbsp;можете отправить на&nbsp;почту:</p><a href="mailto:o.rasseko@gmail.com" class="vacancy_faq_item_flex_mail_a">o.rasseko@gmail.com</a></div></div>'
    },
    {
      title:'Архитектор',
      text:'<p class="vacancy_faq_item_p_bold">От&nbsp;вас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Высшее архитектурное образование (БНТУ, например).</li><li class="vacancy_faq_item_li">Профессиональное владение программами AutoCad, Revit, Adobe Photoshop, SketchUp, базовые навыки 3Ds Max.</li><li class="vacancy_faq_item_li">Опыт ведения проектов от&nbsp;разработки до&nbsp;реализации (от&nbsp;3&nbsp;лет!).</li><li class="vacancy_faq_item_li">Знание строительных материалов, деталей конструкции и&nbsp;соответствующих правил, норм и&nbsp;стандартов качества, применяемых к&nbsp;дизайну интерьеров.</li><li class="vacancy_faq_item_li">Любовь к&nbsp;профессии и&nbsp;желание развиваться в&nbsp;этой сфере.</li></ul><p class="vacancy_faq_item_p_bold">От&nbsp;нас</p><ul class="vacancy_faq_item_ul"><li class="vacancy_faq_item_li">Посещение зарубежных выставок, предприятий, спецпроектов и&nbsp;семинаров.</li><li class="vacancy_faq_item_li">Ведение авторского надзора с&nbsp;посещением реализуемых объектов.</li><li class="vacancy_faq_item_li">Карьерный рост.</li><li class="vacancy_faq_item_li">Обучающие технические семинары, позволяющие углубить знания по&nbsp;строительным материалам, освещению, звуковому оснащению, инженерным системам водоснабжения и&nbsp;отопления, кондиционирования и&nbsp;др.</li><li class="vacancy_faq_item_li">Посещение зарубежных выставок и&nbsp;предприятий.</li></ul><div class="vacancy_faq_item_flex"><div class="vacancy_faq_item_flex_text"><p class="vacancy_faq_item_p">Будет здорово, если перед отправкой резюме и&nbsp;портфолио вы&nbsp;чуть больше узнаете о&nbsp;нашей студии. О&nbsp;нашей специализации и&nbsp;подходе к&nbsp;проектам мы&nbsp;рассказываем в&nbsp;разделах &laquo;Портфолио&raquo; и&nbsp;&laquo;О&nbsp;студии&raquo;. Загляните туда, это поможет составить представление о&nbsp;том, чем вам предстоит заниматься.</p><p class="vacancy_faq_item_p">В&nbsp;нашей команде нет случайных людей. Больше всего в&nbsp;сотрудниках мы&nbsp;ценим готовность трудиться и&nbsp;любовь к&nbsp;дизайну. Чтобы попасть в&nbsp;нашу команду вам нужно будет выполнить небольшое креативное задание. Оно не&nbsp;займет много времени, но&nbsp;поможет нам лучше познакомиться с&nbsp;вами.</p></div><div class="vacancy_faq_item_flex_mail"><p class="vacancy_faq_item_flex_mail_p">Резюме вы&nbsp;можете отправить на&nbsp;почту:</p><a href="mailto:o.rasseko@gmail.com" class="vacancy_faq_item_flex_mail_a">o.rasseko@gmail.com</a></div></div>'
    }
  ];
  return (
      <Accordion config={config} />
  )
}